name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            os:
              - ubuntu20.04
            otp:
              - 25.1.2-2
            elixir:
              - 1.13.4
            arch:
              - amd64
        container: ghcr.io/emqx/emqx-builder/5.0-26:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}

        steps:
        - uses: actions/checkout@v1

        - name: Compile
          run: |
            make

        - name: Concuerror tests
          run : |
            make concuerror_test
